Css
ok-technopolis-autumn-2019/Vyacheslav_Shlyaga pull request #2
Opened 2019-10-15 15:56 UTC by s3ponia

2019-10-20 23:42 UTC, fromanywhere requested changes

2019-10-20 23:42 UTC, fromanywhere commented on index.html
>      <link rel="stylesheet" href="styles.css" media="all" />
Здесь еще сам roboto нужно подключить, fonts.google.com

2019-10-20 23:42 UTC, fromanywhere commented on header.css
> +h1 {
теперь живем по bem, стилизация по классу, не по тегу

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +div.todos-tasks {
все теги убираем, оставляем только классы

2019-10-20 23:42 UTC, fromanywhere commented on header.css
> +  font-family: Roboto;
вообще лучше с фоллбэком писать типа Roboto, sans-serif

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  line-height: 21px;
у меня сомнение, что line-height здесь нужен

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  height: 350px;
ну а если записей больше станет, что будет?

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +li.todos-tasks_list_element,
переписываем селекторы на bem

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  box-shadow: inset 0px -1px 0px #e6e6e6;
здесь лучше взять бордер, несмотря на фигму

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  display: flex;
а нужен ли кнопке флекс?

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  background: url('./icons/close.png') no-repeat center / contain;
здесь нужно подумать про ретиновые дисплеи и подключать четкую графику через media queries

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  width: 16px;
Очень маленькая площадь клика

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  border: none;
А что с клавиатурным фокусом?

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  border-radius: 50%;
К сожалению, так не заработает, нужно делать элемент, который будет стилизоваться, а сам чекбокс скрывать position: absolute; left: -9999px;

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +input.todos-tasks_list_element-status:checked + label.task-name {
здесь придется тогда делать ~ вместо +

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  cursor: pointer;
а по макету там радиокнопок нет, но есть обводка у активного текста. Тот же подход, как с чекбоксами

2019-10-20 23:42 UTC, fromanywhere commented on index.html
> +            <label class="task-name">JS Tools</label>
а в чем была идея делать именно label?

2019-10-20 23:42 UTC, fromanywhere commented on main.css
> +  border: 1px solid #ebdfdf;
в макете такого не было

2019-10-21 10:01 UTC, s3ponia commented on index.html
> +            <label class="task-name">JS Tools</label>
Стилизовать текст по нажатию по-другому не придумал)

2019-10-29 19:06 UTC, fromanywhere requested changes

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +  background: url('./icons/close.png') no-repeat center / contain;
Все еще актуально

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +  color: #CCCCCC;
по высоте бы поле ввода растянуть

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +}
на фокус бы обводку тоже подкрашивать

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +.todos-tasks_list_element-status_view {
Нейминг совсем не по бэму

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +}
а на фокус?

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +.default-null-wrapper {
null-wrapper, серьезно?
![image](https://user-images.githubusercontent.com/1042969/67800313-1bce7900-fa98-11e9-8854-c3dbd0e8b4a9.png)

2019-10-29 19:06 UTC, fromanywhere commented on main.css
> +  font-size: 14px;
цвет вроде тоже отличается

2019-10-29 19:07 UTC, fromanywhere commented on main.css
> +
.task-name рвется 
![image](https://user-images.githubusercontent.com/1042969/67800579-87184b00-fa98-11e9-9f0b-6d31bf65037c.png)

2019-11-18 13:45 UTC, fromanywhere approved these changes

2019-11-18 17:47 UTC, merged